############################
##### Overall workflow #####
############################

# Type of input data (either 'Single' or 'Cohort')
DATA: "Cohort"

# File directories to reference genome and dbSNP database
REFGENOME: "/path/to/reference/human/genome/ucsc.hg19.fasta"
dbSNP: "/path/to/dbSNP/All_20180423.vcf.gz"

# Temporary file directory
TEMPDIR: "/file/path/to/tmp/"

# WES settings (leave blank if analysing other data such as WGS)
WES:
  # Genomic intervals over which to operate
  INTERVALS: ""
  # Padding (in bp) to add to each interval
  PADDING: ""
  
##############################
##### Base recalibration #####
##############################

# Resources used for base recalibration
RECALIBRATION:
  RESOURCES: "--known-sites /path/to/dbSNP/All_20180423.vcf.gz
              --known-sites /path/to/mills/Mills_and_1000G_gold_standard.indels.hg19.sites.vcf.gz
              --known-sites /path/to/1000G/indels/1000G_phase1.indels.hg19.sites.vcf.gz"